apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-system
  namespace: monitoring
spec:
  chart:
    git: https://github.com/denys-kovalchuk/kbot
    ref: main
    path: otel
  values:
    - controller:
        repository: https://github.com/denys-kovalchuk/kbot
        branch: main
        path: otel
